/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.shopmanagebill;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author devra
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    Connection con;
    Statement stm;

    public admin() {
        initComponents();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/shopmanage", "root", "");

            stm = con.createStatement();

        } catch (ClassNotFoundException | SQLException ob) {
            System.out.println("some problem" + ob);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        admitf = new javax.swing.JTextField();
        passtf = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        loginbt = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        errolb = new javax.swing.JLabel();
        pagebt = new javax.swing.JButton();
        addcbt1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\MY JAVA\\Project\\Shopsmanagement\\image\\admin page.jpg")); // NOI18N
        jLabel6.setToolTipText("");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel6.setAutoscrolls(true);
        jLabel6.setDisabledIcon(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("Password ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 302, -1, 30));

        admitf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        admitf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admitfActionPerformed(evt);
            }
        });
        getContentPane().add(admitf, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 238, 271, 41));

        passtf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(passtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 344, 271, 42));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 153));
        jLabel4.setText("Admin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 196, 171, 36));

        loginbt.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        loginbt.setText("Login");
        loginbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtActionPerformed(evt);
            }
        });
        getContentPane().add(loginbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 467, 181, 48));

        jPanel1.setBackground(new java.awt.Color(255, 0, 153));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel2.setText(" Hotel FunFee");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 48)); // NOI18N
        jLabel3.setText("Mr. Devraj Saini");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 48, -1, -1));

        errolb.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        errolb.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(errolb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 243, 43));

        pagebt.setBackground(new java.awt.Color(0, 255, 204));
        pagebt.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        pagebt.setText("Main page ");
        pagebt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pagebtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pagebtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pagebtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pagebtMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pagebtMouseReleased(evt);
            }
        });
        pagebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagebtActionPerformed(evt);
            }
        });
        getContentPane().add(pagebt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 130, 40));

        addcbt1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        addcbt1.setText("Add Cashier");
        addcbt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcbt1ActionPerformed(evt);
            }
        });
        getContentPane().add(addcbt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 467, 181, 48));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\MY JAVA\\Project\\Shopsmanagement\\image\\admin page.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-500, -30, 2030, 940));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admitfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admitfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admitfActionPerformed


    private void loginbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtActionPerformed

        errolb.setForeground(Color.red);

        String admin = admitf.getText().trim();
        String pass = passtf.getText().trim();

        if (admin.isEmpty() || pass.isEmpty()) {
            errolb.setText("Empty details");
        } else {

            if (admin.equals("devraj") && pass.equals("123@dev")) {
                errolb.setForeground(Color.blue);
                errolb.setText("login your page");

            } else {
                errolb.setText("invalid details");
            }

        }
    }//GEN-LAST:event_loginbtActionPerformed

    private void pagebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagebtActionPerformed

        String admin = admitf.getText().trim();
        String pass = passtf.getText().trim();

        if (admin.equals("Devraj") && pass.equals("123@dev")) {
            errolb.setForeground(Color.blue);
            errolb.setText("login your page");

            mainpage mainpa = new mainpage("Devraj");
            mainpa.setVisible(true);
            mainpa.setBounds(10, 20, 990, 700);

            admitf.setText("");
            passtf.setText("");

        } else {
            errolb.setText("After login you access");
        }


    }//GEN-LAST:event_pagebtActionPerformed

    private void addcbt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcbt1ActionPerformed
        // TODO add your handling code here:

        String login = errolb.getText();

        if (login.equals("login your page")) {

            addcash();
        } else {
            errolb.setText("please login");
        }

    }//GEN-LAST:event_addcbt1ActionPerformed

    private void pagebtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagebtMouseEntered

        pagebt.setBackground(Color.red);

    }//GEN-LAST:event_pagebtMouseEntered

    private void pagebtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagebtMouseExited
        // TODO add your handling code here:
        pagebt.setBackground(Color.white);

    }//GEN-LAST:event_pagebtMouseExited

    private void pagebtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagebtMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_pagebtMousePressed

    private void pagebtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagebtMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_pagebtMouseReleased

    private void pagebtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagebtMouseClicked
        // TODO add your handling code here:
        pagebt.setBackground(Color.GREEN);

    }//GEN-LAST:event_pagebtMouseClicked

    public void addcash() {
        int t = 0;
        while (t == 0) {
            String name = JOptionPane.showInputDialog("Enter cashier name");
            String pass = JOptionPane.showInputDialog("Create cashier password");
            String user = JOptionPane.showInputDialog("Create cashier userID");

            if (name == null || name.trim().isEmpty() || pass == null || pass.trim().isEmpty()) {

                if (user == null || user.trim().isEmpty()) {
                    user = "123@";
                }

                errolb.setText("Some details are missing.");

                int res = JOptionPane.showConfirmDialog(rootPane, "You did not type name or password. Click Cancel to exit.", "Warning", JOptionPane.YES_NO_CANCEL_OPTION);

                if (res == JOptionPane.CANCEL_OPTION || res == JOptionPane.CLOSED_OPTION) {
                    break;
                }

            } else {
                try {
                    String sql = "INSERT INTO cashier(name, user_id, `password`) VALUES ('" + name + "', '" + user + "', '" + pass + "');";
                    stm.executeUpdate(sql);

                    errolb.setForeground(Color.BLUE);
                    errolb.setText("Added new cashier.");
                    t = 1; // Exit loop after successful insert
                } catch (SQLException ob) {
                    t = 1;
                    errolb.setForeground(Color.RED);
                    errolb.setText("SQL error: " + ob.getMessage());
                    System.out.println(ob);
                } catch (Exception ob) {
                    t = 1;
                    errolb.setForeground(Color.RED);
                    errolb.setText("Error occurred.");
                    System.out.println(ob);
                }
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcbt1;
    private javax.swing.JTextField admitf;
    private javax.swing.JLabel errolb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginbt;
    private javax.swing.JButton pagebt;
    private javax.swing.JPasswordField passtf;
    // End of variables declaration//GEN-END:variables
}
