/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.shopmanagebill;

import com.google.zxing.Result;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author devra
 */
public class cashier extends javax.swing.JFrame {

    Connection con;
    Statement stm, stm1;

    /**
     * Creates new form cashier
     */
    public cashier() {
        initComponents();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/shopmanage", "root", "");

            stm = con.createStatement();

        } catch (ClassNotFoundException | SQLException ob) {
            System.out.println("some problem" + ob);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        errolb = new javax.swing.JLabel();
        usertf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        loginbt = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        passtf = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        datatl = new javax.swing.JTable();
        databt = new javax.swing.JButton();
        totallb = new javax.swing.JLabel();
        qrlb = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setTitle("Cashier");
        setIconImages(null);
        setSize(new java.awt.Dimension(1000, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("Password ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 312, -1, 30));

        errolb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        errolb.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(errolb, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 555, 211, 30));

        usertf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usertf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertfActionPerformed(evt);
            }
        });
        getContentPane().add(usertf, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 248, 271, 41));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 153));
        jLabel4.setText("User Id");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 206, 171, 36));

        loginbt.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        loginbt.setText("Login");
        loginbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtActionPerformed(evt);
            }
        });
        getContentPane().add(loginbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 181, 48));

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel2.setText(" Hotel FunFee");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(641, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 68, 930, -1));
        getContentPane().add(passtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 354, 271, 42));

        datatl.setAutoCreateRowSorter(true);
        datatl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        datatl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        datatl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {"Total amount ", null}
            },
            new String [] {
                "Ittems", "Rs "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        datatl.setDropMode(javax.swing.DropMode.INSERT);
        datatl.setGridColor(new java.awt.Color(51, 51, 51));
        datatl.setName("total items"); // NOI18N
        datatl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        datatl.setShowGrid(true);
        datatl.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(datatl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 300, 350));

        databt.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        databt.setText("Data");
        databt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databtActionPerformed(evt);
            }
        });
        getContentPane().add(databt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 140, 50));

        totallb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totallb.setForeground(new java.awt.Color(255, 0, 255));
        getContentPane().add(totallb, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 570, 460, 40));

        qrlb.setFont(new java.awt.Font("Segoe UI Emoji", 2, 18)); // NOI18N
        qrlb.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(qrlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 328, 300, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\MY JAVA\\Project\\Shopsmanagement\\image\\cashier image.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -20, 1050, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usertfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertfActionPerformed


    private void loginbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtActionPerformed
        errolb.setForeground(Color.red);

        String user = usertf.getText().trim();
        String pass = passtf.getText().trim();
        ResultSet res;

        if (user.isEmpty() || pass.isEmpty()) {
            errolb.setText("Empty login details");
        } else {
            try {
                String cashier = "select * from cashier where name= ?";

                PreparedStatement ps = con.prepareStatement(cashier);
                ps.setString(1, user);

                res = ps.executeQuery();

                if (res.next()) {

                    String pw = res.getString("password");

                    if (pw.equals(pass)) {
                        errolb.setForeground(Color.blue);

                        errolb.setText("Login Successfully");

                    } else {
                        errolb.setText("password incorect ");

                    }

                } else {
                    if ("1845".equals(pass) && "devrajsaini".equals(user)) {
                        errolb.setForeground(Color.blue);

                        errolb.setText("Login Successfully");
                    } else {
                        errolb.setText("Invalid details");
                    }

                }

                res.close();
                ps.close();
            } catch (SQLException ob) {
                errolb.setText("some problem in fetching data");
                System.out.print("some=" + ob);

            } catch (NullPointerException ob) {
                errolb.setText("some problem in fetching data");

            }
        }
    }//GEN-LAST:event_loginbtActionPerformed

    private void databtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databtActionPerformed
        String check = errolb.getText();
        if (check.equals("Login Successfully")) {

            getdatars();

            errolb.setForeground(Color.blue);

            errolb.setText("wel-come");
            int choose = JOptionPane.showConfirmDialog(rootPane, "are you close the page", "close confirm", JOptionPane.OK_CANCEL_OPTION);
            if (choose == JOptionPane.OK_OPTION) {

                String del = "delete from billing;";
                try {
                    stm1.executeUpdate(del);
                } catch (SQLException | NullPointerException ob) {
                    errolb.setText("fetching in refresh data");

                }
                this.dispose();
            } else {
                mainpage mainpa = new mainpage("Old guest");
                mainpa.setVisible(true);
                mainpa.setBounds(10, 20, 990, 700);

            }
        } else {
            errolb.setText("please login now");

        }

    }//GEN-LAST:event_databtActionPerformed

    ResultSet res;

    public void getdatars() {
        int offer, tot = 0;
        int money = 0;
        String total = "select sum(price) from billing";
        try {
            res = stm.executeQuery(total);
            if (res.next()) {

                tot = res.getInt(1);
                //exception NullPointerException
                totallb.setText("Total price : " + tot);

                money = JOptionPane.showConfirmDialog(rootPane, " today offer check", "money page", JOptionPane.YES_NO_OPTION);

                if (money == JOptionPane.YES_OPTION) {
                    int t = 0;
                    while (t == 0) {
                        String x = JOptionPane.showInputDialog(null, "enter offer in percent% ");

                        offer = Integer.parseInt(x);

                        int to1 = (tot / 100) * offer;
                        totallb.setText("Total price with offer" + offer + "% : " + (tot - to1));
                               qrlb.setText("Upi-id 9111xs4930@ybl");

                        t = 1;
                    }
                }
            } else {
                totallb.setText("Total price not found  ");

            }
        } catch (NumberFormatException ob) {
            errolb.setText("error in calculation");

        } catch (SQLException | NullPointerException ex) {
            Logger.getLogger(cashier.class.getName()).log(Level.SEVERE, null, ex);
            errolb.setText("error in calculation");

        }

        if (money == JOptionPane.NO_OPTION || money == JOptionPane.CLOSED_OPTION) {
            totallb.setText("Total price without no offer : " + tot);
             qrlb.setText("Upi-id 9111xs4930@ybl");

        }
          
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                cashier cash = new cashier();
                cash.setBounds(250, 30, 1000, 800);
                cash.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton databt;
    private javax.swing.JTable datatl;
    private javax.swing.JLabel errolb;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loginbt;
    private javax.swing.JPasswordField passtf;
    private javax.swing.JLabel qrlb;
    private javax.swing.JLabel totallb;
    private javax.swing.JTextField usertf;
    // End of variables declaration//GEN-END:variables
}
