/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.shopmanagebill;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author devra
 */
public class guest extends javax.swing.JFrame {

    Connection con;
    Statement stm;

    /**
     * Creates new form guest
     */
    public guest() {
        initComponents();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/shopmanage", "root", "");

            stm = con.createStatement();

        } catch (ClassNotFoundException | SQLException ob) {
            System.out.println("some problem" + ob);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        usertf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        singlb = new javax.swing.JLabel();
        passtf = new javax.swing.JTextField();
        loginbt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        errolb = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setTitle("For customer");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(400, 200));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SimSun-ExtB", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText(" Hotel FunFee");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 270, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("Password ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, 30));

        usertf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(usertf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 255, 39));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 153));
        jLabel4.setText("Guest User Id");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, 30));

        singlb.setBackground(new java.awt.Color(51, 255, 51));
        singlb.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        singlb.setForeground(new java.awt.Color(255, 0, 0));
        singlb.setText("Sign-up now");
        singlb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                singlbMouseClicked(evt);
            }
        });
        getContentPane().add(singlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 476, 101, 43));

        passtf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passtfActionPerformed(evt);
            }
        });
        getContentPane().add(passtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 255, 39));

        loginbt.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        loginbt.setText("Login");
        loginbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtActionPerformed(evt);
            }
        });
        getContentPane().add(loginbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 113, 37));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Not a member?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 480, -1, 30));

        errolb.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        errolb.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(errolb, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 439, 238, 31));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\MY JAVA\\Project\\Shopsmanagement\\image\\guestlogin9.jpeg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passtfActionPerformed

    private void loginbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtActionPerformed

        String user = usertf.getText().trim();
        String pass = passtf.getText().trim();
        ResultSet res;

        // continue user data dega or ham mysql se match kar ke layenge
        if (user.isEmpty() || pass.isEmpty()) {
            errolb.setText("Invalid login details");
        }
        try {
            String datauser = "select * from singup where name= ?";

            PreparedStatement ps = con.prepareStatement(datauser);
            ps.setString(1, user);

            res = ps.executeQuery();

            if (res.next()) {

                String pw = res.getString("password");

                if (pw.equals(pass) || ("1845".equals(pass) && "devrajsaini".equals(user))) {
                    errolb.setText("Login Successfully");

                    mainpage mainpa = new mainpage(user);
                    mainpa.setVisible(true);
                    mainpa.setBounds(10, 20, 990, 700);
                    this.dispose();

                } else {
                    errolb.setText("Incorrect details");
                }
            } else {
                errolb.setText("user not found ");

            }

            res.close();
            ps.close();
        } catch (SQLException ob) {
            errolb.setText("some problem in fetchung data");
            System.out.print("some=" + ob);

        }


    }//GEN-LAST:event_loginbtActionPerformed


    private void singlbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_singlbMouseClicked

        errolb.setText("sign up");
        this.dispose();
        singupguest gu = new singupguest();
        gu.setVisible(true);
        gu.setBounds(300, 10, 740, 673);

    }//GEN-LAST:event_singlbMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                guest gu = new guest();
                gu.setVisible(true);
                gu.setBounds(250, 90, 590, 610);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errolb;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton loginbt;
    private javax.swing.JTextField passtf;
    private javax.swing.JLabel singlb;
    private javax.swing.JTextField usertf;
    // End of variables declaration//GEN-END:variables
}
