/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.shopmanagebill;

/**
 *
 * @author devra
 */
public class singupp extends javax.swing.JFrame {

    /**
     * Creates new form singupp
     */
    public singupp() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jFrame3 = new javax.swing.JFrame();
        jFrame4 = new javax.swing.JFrame();
        jFrame5 = new javax.swing.JFrame();
        jDialog3 = new javax.swing.JDialog();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        b1guest = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        b1cash = new javax.swing.JButton();
        b1admin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login page");
        setIconImages(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 3, 2, 3, new java.awt.Color(0, 0, 0)));
        jPanel2.setName(""); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("User Authentication");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 192, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 31, 320, 64));

        b1guest.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b1guest.setText("Guest");
        buttonGroup1.add(b1guest);
        b1guest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1guestActionPerformed(evt);
            }
        });
        getContentPane().add(b1guest, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 175, 158, 37));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 255));
        jLabel5.setText(" User.....");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 116, 86, -1));

        b1cash.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b1cash.setText("Cashier");
        buttonGroup1.add(b1cash);
        b1cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1cashActionPerformed(evt);
            }
        });
        getContentPane().add(b1cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 267, 158, 37));

        b1admin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b1admin.setText("Admin");
        buttonGroup1.add(b1admin);
        b1admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1adminActionPerformed(evt);
            }
        });
        getContentPane().add(b1admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 158, 37));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\MY JAVA\\Project\\Shopsmanagement\\image\\firstsign.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 690, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1adminActionPerformed

        admin cash1 = new admin();
        cash1.setBounds(250, 30, 900, 700);
        cash1.setVisible(true);


    }//GEN-LAST:event_b1adminActionPerformed

    private void b1cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1cashActionPerformed
        cashier cash = new cashier();
        cash.setBounds(250, 30, 1000, 800);
        cash.setVisible(true);


    }//GEN-LAST:event_b1cashActionPerformed

    private void b1guestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1guestActionPerformed
        guest g1 = new guest();
        g1.setVisible(true);


    }//GEN-LAST:event_b1guestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(singupp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(singupp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(singupp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(singupp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                singupp ob = new singupp();
                ob.setVisible(true);
                //  ob.setSize(700,660);
                ob.setBounds(500, 40, 700, 600);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1admin;
    private javax.swing.JButton b1cash;
    private javax.swing.JButton b1guest;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JFrame jFrame5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
