/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.shopmanagebill;

import java.awt.Color;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author devra
 */
public class singupguest extends javax.swing.JFrame {

    Connection con;
    Statement stm;

    /**
     * Creates new form singup
     */
    public singupguest() {
        initComponents();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/shopmanage", "root", "");

            stm = con.createStatement();

        } catch (ClassNotFoundException | SQLException ob) {
            System.out.println("some problem" + ob);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        phontf = new javax.swing.JTextField();
        passtf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        phonlb = new javax.swing.JLabel();
        succ = new javax.swing.JLabel();
        passlb = new javax.swing.JLabel();
        loginbt1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("SimSun-ExtB", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText(" Hotel FunFee");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.black);
        setLocation(new java.awt.Point(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("SimSun-ExtB", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText(" Hotel FunFee");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 22, 537, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("~~WEL COME~~");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 121, 167, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Password ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 107, 29));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Urname");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 90, 29));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Phone Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 144, 29));

        nametf.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        nametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametfActionPerformed(evt);
            }
        });
        getContentPane().add(nametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 220, 36));

        phontf.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        phontf.setText("91+ ");
        phontf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phontfActionPerformed(evt);
            }
        });
        getContentPane().add(phontf, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 220, 36));

        passtf.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        passtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passtfActionPerformed(evt);
            }
        });
        getContentPane().add(passtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 220, 36));

        jButton1.setBackground(new java.awt.Color(51, 255, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 469, 134, 45));

        phonlb.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        phonlb.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(phonlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 210, 30));

        succ.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        succ.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(succ, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 360, 38));

        passlb.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        passlb.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(passlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 180, 26));

        loginbt1.setBackground(new java.awt.Color(0, 255, 204));
        loginbt1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        loginbt1.setText("Login");
        loginbt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbt1ActionPerformed(evt);
            }
        });
        getContentPane().add(loginbt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 590, 113, 37));

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\MY JAVA\\Project\\Shopsmanagement\\image\\singupp.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 0, 960, 930));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametfActionPerformed

    private void phontfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phontfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phontfActionPerformed

    private void passtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passtfActionPerformed

    public boolean chek(String password1) {
        boolean c = false;
        char p[] = password1.toCharArray();
        for (int i = 0; i < password1.length(); i += 1) {
            if (p[i] == '@') {

                c = true;
                break;
            }
        }
        return c;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        succ.setForeground(Color.red);

        boolean start = false, start1 = false, start3 = false;
        String password1 = passtf.getText().trim();
        String name = nametf.getText().trim();
        String phone = phontf.getText().trim();
        int z = phone.length();
        if ("".equals(password1)) {
            passlb.setText("password can't empty");
        } else {
            if (chek(password1)) {

                passlb.setText("");
                start3 = true;

            } else {
                passlb.setText("use @ in password ");

            }
        }
        if (z == 14) {
            phonlb.setText("");
            start = true;
        } else {
            phonlb.setText("type correct number");

        }
        if (!nametf.equals("")) {
            start1 = true;
        }
        if (start == true && start1 == true && start3 == true) {
            String s = "insert into singup(name,`password`,phone)values('" + name + "','" + password1 + "','" + phone + "');";

            try {
                stm.executeUpdate(s);
                succ.setForeground(Color.blue);

                succ.setText("Registration Successfully");

            } catch (SQLException ob) {
                succ.setText("some problem in update" + ob);

            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void loginbt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbt1ActionPerformed
        guest g1 = new guest();
        g1.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_loginbt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(singupguest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(singupguest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(singupguest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(singupguest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                singupguest gu = new singupguest();
                gu.setVisible(true);
                gu.setBounds(250, 90, 740, 673);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton loginbt1;
    private javax.swing.JTextField nametf;
    private javax.swing.JLabel passlb;
    private javax.swing.JTextField passtf;
    private javax.swing.JLabel phonlb;
    private javax.swing.JTextField phontf;
    private javax.swing.JLabel succ;
    // End of variables declaration//GEN-END:variables
}
